version: "3.7"
services:

  books.local:
    build:
      args:
        user: books
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: books-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - proxy

  books_nginx:
    image: nginx:1.17-alpine
    container_name: books-nginx
    restart: unless-stopped
    ports:
      - "8011:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - proxy

  books_db:
    image: mysql:5.7
    container_name: books-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - proxy


volumes:
  mysql-data:

networks:
  proxy:
    external:
      name: lumengateway
